// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"
)

type Session struct {
	UserID         int64     `json:"user_id"`
	Token          string    `json:"token"`
	AbsoluteExpiry time.Time `json:"absolute_expiry"`
	IdleExpiry     time.Time `json:"idle_expiry"`
}

type User struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Email      string    `json:"email"`
	Password   string    `json:"password"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
}
