// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_queries.sql

package queries

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO
    sessions (user_id, token, absolute_expiry, idle_expiry)
VALUES
    (?1, ?2, ?3, ?4)
RETURNING
    user_id, token, absolute_expiry, idle_expiry
`

type CreateSessionParams struct {
	UserID         int64     `json:"user_id"`
	Token          string    `json:"token"`
	AbsoluteExpiry time.Time `json:"absolute_expiry"`
	IdleExpiry     time.Time `json:"idle_expiry"`
}

// CreateSession creates a new session for a user
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.Token,
		arg.AbsoluteExpiry,
		arg.IdleExpiry,
	)
	var i Session
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.AbsoluteExpiry,
		&i.IdleExpiry,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE
    absolute_expiry < datetime('now')
    OR idle_expiry < datetime('now')
`

// DeleteExpiredSessions deletes all expired sessions
func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE
    token = ?1
`

// DeleteSession deletes a session by token
func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getSessionById = `-- name: GetSessionById :one
SELECT
    user_id, token, absolute_expiry, idle_expiry
FROM
    sessions
WHERE
    token = ?1
`

// GetSessionById retrieve an unexperied session
func (q *Queries) GetSessionById(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, token)
	var i Session
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.AbsoluteExpiry,
		&i.IdleExpiry,
	)
	return i, err
}

const getUserBySessionId = `-- name: GetUserBySessionId :one
SELECT
    users.id, users.username, users.email, users.password, users.created_at, users.modified_at
FROM
    users
JOIN
    sessions ON users.id = sessions.user_id
WHERE
    sessions.token = ?1 AND
    sessions.absolute_expiry > datetime('now') AND
    sessions.idle_expiry > datetime('now')
`

// GetUserBySessionId retrieves a user by session token
func (q *Queries) GetUserBySessionId(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySessionId, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateSessionIdleExpiry = `-- name: UpdateSessionIdleExpiry :exec
UPDATE sessions
SET idle_expiry = ?1
WHERE
    token = ?2
`

type UpdateSessionIdleExpiryParams struct {
	IdleExpiry time.Time `json:"idle_expiry"`
	Token      string    `json:"token"`
}

// UpdateSessionIdleExpiry updates the idle expiry of a session
func (q *Queries) UpdateSessionIdleExpiry(ctx context.Context, arg UpdateSessionIdleExpiryParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionIdleExpiry, arg.IdleExpiry, arg.Token)
	return err
}
