// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_queries.sql

package queries

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (email, username, password)
VALUES
    (?1, ?2, ?3)
RETURNING
    id, username, email, password, created_at, modified_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

// CreateUser creates a new user
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT
    id, username, email, password, created_at, modified_at
FROM
    users
WHERE
    email = ?1
    OR username = ?1
LIMIT
    1
`

// GetUserByEmailOrUsername retrieves user by email or username
func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, input string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailOrUsername, input)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    id, username, email, password, created_at, modified_at
FROM
    users
WHERE
    id = ?1
LIMIT
    1
`

// GetUserById retrieves user by id
func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = ?1,
    username = ?2,
    password = ?3,
    modified_at = datetime()
WHERE
    id = ?4
RETURNING
    id, username, email, password, created_at, modified_at
`

type UpdateUserParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

// UpdateUser updates user information
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
