// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_queries.sql

package queries

import (
	"context"
)

const createPrincipal = `-- name: CreatePrincipal :one
INSERT INTO
    users (email, username, password, role)
VALUES
    (?1, ?2, ?3, ?4)
RETURNING
    id, username, email, password, created_at, modified_at, role
`

type CreatePrincipalParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

// CreatePrincipal creates a new user
func (q *Queries) CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createPrincipal,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Role,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT
    id, username, email, password, created_at, modified_at, role
FROM
    users
WHERE
    email = ?1
    OR username = ?1
LIMIT
    1
`

// GetUserByEmailOrUsername retrieves user by email or username
func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, input string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailOrUsername, input)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Role,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    id, username, email, password, created_at, modified_at, role
FROM
    users
WHERE
    id = ?1
LIMIT
    1
`

// GetUserById retrieves user by id
func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Role,
	)
	return i, err
}

const updatePrincipal = `-- name: UpdatePrincipal :one
UPDATE users
SET
    email = COALESCE(?1, email),
    username = COALESCE(?2, username),
    password = COALESCE(?3, password),
    role = COALESCE(?4, role),
    modified_at = datetime()
WHERE
    id = ?5
RETURNING
    id, username, email, password, created_at, modified_at, role
`

type UpdatePrincipalParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Role     string `json:"role"`
	ID       int64  `json:"id"`
}

// UpdatePrincipal updates user information
func (q *Queries) UpdatePrincipal(ctx context.Context, arg UpdatePrincipalParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updatePrincipal,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Role,
	)
	return i, err
}
