# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  run:
    desc: "Run the backend process"
    cmds:
      - go run ./cmd/api
    env:
        LOG_LEVEL: -4
    silent: true
  test:
    desc: "Run the test suit (unit and integration tests)"
    cmds:
      - go test ./...
    silent: true
  unit-test:
    desc: "Run the unit test suit"
    cmds:
      - go test -short ./...
    silent: true
