// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"sync"
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked Service
//		mockedService := &ServiceMock{
//			LoginFunc: func(ctx context.Context, req LoginRequest) (string, error) {
//				panic("mock out the Login method")
//			},
//			LogoutFunc: func(ctx context.Context, sessionToken string) error {
//				panic("mock out the Logout method")
//			},
//			RegisterFunc: func(ctx context.Context, req RegisterRequest) (*RegisterResponse, error) {
//				panic("mock out the Register method")
//			},
//			VerifySessionFunc: func(ctx context.Context, sessionToken string) (*Principal, error) {
//				panic("mock out the VerifySession method")
//			},
//		}
//
//		// use mockedService in code that requires Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, req LoginRequest) (string, error)

	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context, sessionToken string) error

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, req RegisterRequest) (*RegisterResponse, error)

	// VerifySessionFunc mocks the VerifySession method.
	VerifySessionFunc func(ctx context.Context, sessionToken string) (*Principal, error)

	// calls tracks calls to the methods.
	calls struct {
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req LoginRequest
		}
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionToken is the sessionToken argument value.
			SessionToken string
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req RegisterRequest
		}
		// VerifySession holds details about calls to the VerifySession method.
		VerifySession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionToken is the sessionToken argument value.
			SessionToken string
		}
	}
	lockLogin         sync.RWMutex
	lockLogout        sync.RWMutex
	lockRegister      sync.RWMutex
	lockVerifySession sync.RWMutex
}

// Login calls LoginFunc.
func (mock *ServiceMock) Login(ctx context.Context, req LoginRequest) (string, error) {
	if mock.LoginFunc == nil {
		panic("ServiceMock.LoginFunc: method is nil but Service.Login was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req LoginRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, req)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedService.LoginCalls())
func (mock *ServiceMock) LoginCalls() []struct {
	Ctx context.Context
	Req LoginRequest
} {
	var calls []struct {
		Ctx context.Context
		Req LoginRequest
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Logout calls LogoutFunc.
func (mock *ServiceMock) Logout(ctx context.Context, sessionToken string) error {
	if mock.LogoutFunc == nil {
		panic("ServiceMock.LogoutFunc: method is nil but Service.Logout was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		SessionToken string
	}{
		Ctx:          ctx,
		SessionToken: sessionToken,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx, sessionToken)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedService.LogoutCalls())
func (mock *ServiceMock) LogoutCalls() []struct {
	Ctx          context.Context
	SessionToken string
} {
	var calls []struct {
		Ctx          context.Context
		SessionToken string
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *ServiceMock) Register(ctx context.Context, req RegisterRequest) (*RegisterResponse, error) {
	if mock.RegisterFunc == nil {
		panic("ServiceMock.RegisterFunc: method is nil but Service.Register was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req RegisterRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, req)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedService.RegisterCalls())
func (mock *ServiceMock) RegisterCalls() []struct {
	Ctx context.Context
	Req RegisterRequest
} {
	var calls []struct {
		Ctx context.Context
		Req RegisterRequest
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// VerifySession calls VerifySessionFunc.
func (mock *ServiceMock) VerifySession(ctx context.Context, sessionToken string) (*Principal, error) {
	if mock.VerifySessionFunc == nil {
		panic("ServiceMock.VerifySessionFunc: method is nil but Service.VerifySession was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		SessionToken string
	}{
		Ctx:          ctx,
		SessionToken: sessionToken,
	}
	mock.lockVerifySession.Lock()
	mock.calls.VerifySession = append(mock.calls.VerifySession, callInfo)
	mock.lockVerifySession.Unlock()
	return mock.VerifySessionFunc(ctx, sessionToken)
}

// VerifySessionCalls gets all the calls that were made to VerifySession.
// Check the length with:
//
//	len(mockedService.VerifySessionCalls())
func (mock *ServiceMock) VerifySessionCalls() []struct {
	Ctx          context.Context
	SessionToken string
} {
	var calls []struct {
		Ctx          context.Context
		SessionToken string
	}
	mock.lockVerifySession.RLock()
	calls = mock.calls.VerifySession
	mock.lockVerifySession.RUnlock()
	return calls
}
