// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"context"
	"sync"
	"time"
)

// Ensure, that principalRepositoryMock does implement principalRepository.
// If this is not the case, regenerate this file with moq.
var _ principalRepository = &principalRepositoryMock{}

// principalRepositoryMock is a mock implementation of principalRepository.
//
//	func TestSomethingThatUsesprincipalRepository(t *testing.T) {
//
//		// make and configure a mocked principalRepository
//		mockedprincipalRepository := &principalRepositoryMock{
//			CreatePrincipalFunc: func(ctx context.Context, principal Principal) (*Principal, error) {
//				panic("mock out the CreatePrincipal method")
//			},
//			FindPrincipalByEmailOrUsernameFunc: func(ctx context.Context, token string) (*Principal, error) {
//				panic("mock out the FindPrincipalByEmailOrUsername method")
//			},
//		}
//
//		// use mockedprincipalRepository in code that requires principalRepository
//		// and then make assertions.
//
//	}
type principalRepositoryMock struct {
	// CreatePrincipalFunc mocks the CreatePrincipal method.
	CreatePrincipalFunc func(ctx context.Context, principal Principal) (*Principal, error)

	// FindPrincipalByEmailOrUsernameFunc mocks the FindPrincipalByEmailOrUsername method.
	FindPrincipalByEmailOrUsernameFunc func(ctx context.Context, token string) (*Principal, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreatePrincipal holds details about calls to the CreatePrincipal method.
		CreatePrincipal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Principal is the principal argument value.
			Principal Principal
		}
		// FindPrincipalByEmailOrUsername holds details about calls to the FindPrincipalByEmailOrUsername method.
		FindPrincipalByEmailOrUsername []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
	}
	lockCreatePrincipal                sync.RWMutex
	lockFindPrincipalByEmailOrUsername sync.RWMutex
}

// CreatePrincipal calls CreatePrincipalFunc.
func (mock *principalRepositoryMock) CreatePrincipal(ctx context.Context, principal Principal) (*Principal, error) {
	if mock.CreatePrincipalFunc == nil {
		panic("principalRepositoryMock.CreatePrincipalFunc: method is nil but principalRepository.CreatePrincipal was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Principal Principal
	}{
		Ctx:       ctx,
		Principal: principal,
	}
	mock.lockCreatePrincipal.Lock()
	mock.calls.CreatePrincipal = append(mock.calls.CreatePrincipal, callInfo)
	mock.lockCreatePrincipal.Unlock()
	return mock.CreatePrincipalFunc(ctx, principal)
}

// CreatePrincipalCalls gets all the calls that were made to CreatePrincipal.
// Check the length with:
//
//	len(mockedprincipalRepository.CreatePrincipalCalls())
func (mock *principalRepositoryMock) CreatePrincipalCalls() []struct {
	Ctx       context.Context
	Principal Principal
} {
	var calls []struct {
		Ctx       context.Context
		Principal Principal
	}
	mock.lockCreatePrincipal.RLock()
	calls = mock.calls.CreatePrincipal
	mock.lockCreatePrincipal.RUnlock()
	return calls
}

// FindPrincipalByEmailOrUsername calls FindPrincipalByEmailOrUsernameFunc.
func (mock *principalRepositoryMock) FindPrincipalByEmailOrUsername(ctx context.Context, token string) (*Principal, error) {
	if mock.FindPrincipalByEmailOrUsernameFunc == nil {
		panic("principalRepositoryMock.FindPrincipalByEmailOrUsernameFunc: method is nil but principalRepository.FindPrincipalByEmailOrUsername was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockFindPrincipalByEmailOrUsername.Lock()
	mock.calls.FindPrincipalByEmailOrUsername = append(mock.calls.FindPrincipalByEmailOrUsername, callInfo)
	mock.lockFindPrincipalByEmailOrUsername.Unlock()
	return mock.FindPrincipalByEmailOrUsernameFunc(ctx, token)
}

// FindPrincipalByEmailOrUsernameCalls gets all the calls that were made to FindPrincipalByEmailOrUsername.
// Check the length with:
//
//	len(mockedprincipalRepository.FindPrincipalByEmailOrUsernameCalls())
func (mock *principalRepositoryMock) FindPrincipalByEmailOrUsernameCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockFindPrincipalByEmailOrUsername.RLock()
	calls = mock.calls.FindPrincipalByEmailOrUsername
	mock.lockFindPrincipalByEmailOrUsername.RUnlock()
	return calls
}

// Ensure, that sessionStoreMock does implement sessionStore.
// If this is not the case, regenerate this file with moq.
var _ sessionStore = &sessionStoreMock{}

// sessionStoreMock is a mock implementation of sessionStore.
//
//	func TestSomethingThatUsessessionStore(t *testing.T) {
//
//		// make and configure a mocked sessionStore
//		mockedsessionStore := &sessionStoreMock{
//			CreateSessionFunc: func(ctx context.Context, principalID int64) (*Session, error) {
//				panic("mock out the CreateSession method")
//			},
//			DeleteSessionFunc: func(ctx context.Context, sessionToken string) error {
//				panic("mock out the DeleteSession method")
//			},
//			GetSessionFunc: func(ctx context.Context, sessionToken string) (*Principal, error) {
//				panic("mock out the GetSession method")
//			},
//			RefreshSessionFunc: func(ctx context.Context, sessionToken string) (time.Time, error) {
//				panic("mock out the RefreshSession method")
//			},
//		}
//
//		// use mockedsessionStore in code that requires sessionStore
//		// and then make assertions.
//
//	}
type sessionStoreMock struct {
	// CreateSessionFunc mocks the CreateSession method.
	CreateSessionFunc func(ctx context.Context, principalID int64) (*Session, error)

	// DeleteSessionFunc mocks the DeleteSession method.
	DeleteSessionFunc func(ctx context.Context, sessionToken string) error

	// GetSessionFunc mocks the GetSession method.
	GetSessionFunc func(ctx context.Context, sessionToken string) (*Principal, error)

	// RefreshSessionFunc mocks the RefreshSession method.
	RefreshSessionFunc func(ctx context.Context, sessionToken string) (time.Time, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateSession holds details about calls to the CreateSession method.
		CreateSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PrincipalID is the principalID argument value.
			PrincipalID int64
		}
		// DeleteSession holds details about calls to the DeleteSession method.
		DeleteSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionToken is the sessionToken argument value.
			SessionToken string
		}
		// GetSession holds details about calls to the GetSession method.
		GetSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionToken is the sessionToken argument value.
			SessionToken string
		}
		// RefreshSession holds details about calls to the RefreshSession method.
		RefreshSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionToken is the sessionToken argument value.
			SessionToken string
		}
	}
	lockCreateSession  sync.RWMutex
	lockDeleteSession  sync.RWMutex
	lockGetSession     sync.RWMutex
	lockRefreshSession sync.RWMutex
}

// CreateSession calls CreateSessionFunc.
func (mock *sessionStoreMock) CreateSession(ctx context.Context, principalID int64) (*Session, error) {
	if mock.CreateSessionFunc == nil {
		panic("sessionStoreMock.CreateSessionFunc: method is nil but sessionStore.CreateSession was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		PrincipalID int64
	}{
		Ctx:         ctx,
		PrincipalID: principalID,
	}
	mock.lockCreateSession.Lock()
	mock.calls.CreateSession = append(mock.calls.CreateSession, callInfo)
	mock.lockCreateSession.Unlock()
	return mock.CreateSessionFunc(ctx, principalID)
}

// CreateSessionCalls gets all the calls that were made to CreateSession.
// Check the length with:
//
//	len(mockedsessionStore.CreateSessionCalls())
func (mock *sessionStoreMock) CreateSessionCalls() []struct {
	Ctx         context.Context
	PrincipalID int64
} {
	var calls []struct {
		Ctx         context.Context
		PrincipalID int64
	}
	mock.lockCreateSession.RLock()
	calls = mock.calls.CreateSession
	mock.lockCreateSession.RUnlock()
	return calls
}

// DeleteSession calls DeleteSessionFunc.
func (mock *sessionStoreMock) DeleteSession(ctx context.Context, sessionToken string) error {
	if mock.DeleteSessionFunc == nil {
		panic("sessionStoreMock.DeleteSessionFunc: method is nil but sessionStore.DeleteSession was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		SessionToken string
	}{
		Ctx:          ctx,
		SessionToken: sessionToken,
	}
	mock.lockDeleteSession.Lock()
	mock.calls.DeleteSession = append(mock.calls.DeleteSession, callInfo)
	mock.lockDeleteSession.Unlock()
	return mock.DeleteSessionFunc(ctx, sessionToken)
}

// DeleteSessionCalls gets all the calls that were made to DeleteSession.
// Check the length with:
//
//	len(mockedsessionStore.DeleteSessionCalls())
func (mock *sessionStoreMock) DeleteSessionCalls() []struct {
	Ctx          context.Context
	SessionToken string
} {
	var calls []struct {
		Ctx          context.Context
		SessionToken string
	}
	mock.lockDeleteSession.RLock()
	calls = mock.calls.DeleteSession
	mock.lockDeleteSession.RUnlock()
	return calls
}

// GetSession calls GetSessionFunc.
func (mock *sessionStoreMock) GetSession(ctx context.Context, sessionToken string) (*Principal, error) {
	if mock.GetSessionFunc == nil {
		panic("sessionStoreMock.GetSessionFunc: method is nil but sessionStore.GetSession was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		SessionToken string
	}{
		Ctx:          ctx,
		SessionToken: sessionToken,
	}
	mock.lockGetSession.Lock()
	mock.calls.GetSession = append(mock.calls.GetSession, callInfo)
	mock.lockGetSession.Unlock()
	return mock.GetSessionFunc(ctx, sessionToken)
}

// GetSessionCalls gets all the calls that were made to GetSession.
// Check the length with:
//
//	len(mockedsessionStore.GetSessionCalls())
func (mock *sessionStoreMock) GetSessionCalls() []struct {
	Ctx          context.Context
	SessionToken string
} {
	var calls []struct {
		Ctx          context.Context
		SessionToken string
	}
	mock.lockGetSession.RLock()
	calls = mock.calls.GetSession
	mock.lockGetSession.RUnlock()
	return calls
}

// RefreshSession calls RefreshSessionFunc.
func (mock *sessionStoreMock) RefreshSession(ctx context.Context, sessionToken string) (time.Time, error) {
	if mock.RefreshSessionFunc == nil {
		panic("sessionStoreMock.RefreshSessionFunc: method is nil but sessionStore.RefreshSession was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		SessionToken string
	}{
		Ctx:          ctx,
		SessionToken: sessionToken,
	}
	mock.lockRefreshSession.Lock()
	mock.calls.RefreshSession = append(mock.calls.RefreshSession, callInfo)
	mock.lockRefreshSession.Unlock()
	return mock.RefreshSessionFunc(ctx, sessionToken)
}

// RefreshSessionCalls gets all the calls that were made to RefreshSession.
// Check the length with:
//
//	len(mockedsessionStore.RefreshSessionCalls())
func (mock *sessionStoreMock) RefreshSessionCalls() []struct {
	Ctx          context.Context
	SessionToken string
} {
	var calls []struct {
		Ctx          context.Context
		SessionToken string
	}
	mock.lockRefreshSession.RLock()
	calls = mock.calls.RefreshSession
	mock.lockRefreshSession.RUnlock()
	return calls
}
