// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package gen

import (
	"context"
	"time"
)

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO sessions (user_id, id, created_at)
    VALUES (?1, ?2, ?3)
`

type CreateAuthSessionParams struct {
	UserID    int64
	TokenHash []byte
	CreatedAt time.Time
}

// CreateAuthSession creates a new authentication session for a principal. Return the id of the newly created session.
func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAuthSession, arg.UserID, arg.TokenHash, arg.CreatedAt)
	return err
}

const createPrincipal = `-- name: CreatePrincipal :one
INSERT INTO users (username, email, password_hash, created_at)
    VALUES (?1, ?2, ?3, ?4)
    RETURNING id
`

type CreatePrincipalParams struct {
	Username     string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
}

// CreatePrincipal creates a new principal in the database. Return the id of the newly created principal.
func (q *Queries) CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPrincipal,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPrincipalByUsernameOrEmail = `-- name: GetPrincipalByUsernameOrEmail :one
SELECT id, username, email, password_hash, created_at, updated_at FROM principals WHERE username = ?1 OR email = ?1
`

// GetPrincipalByUsernameOrEmail retrieves a principal by username or email. Return the principal if found, otherwise return null.
func (q *Queries) GetPrincipalByUsernameOrEmail(ctx context.Context, token string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByUsernameOrEmail, token)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
