// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gen

import (
	"database/sql"
	"time"
)

type Principal struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
}

type Session struct {
	ID        []byte
	UserID    int64
	CreatedAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
}
